### ISSUE TITLE
`sync-rebuild`: fails when run from another user

### ISSUE THREAD

**Issue by AlexKurisu** [AladW/aurutils#1083]
Trying to run new `sync-rebuild` script from another user (via `sudo`) results in the following error:
```
/usr/lib/aurutils/aur-sync: line 503: /dev/stdout: Permission denied
Traceback (most recent call last):
  File "/home/apkg/./sync-rebuild", line 252, in <module>
    main({i:1 for i in args.targets}, args.database, args.fail_fast, args.no_sync)
  File "/home/apkg/./sync-rebuild", line 219, in main
    subprocess.run(sync_cmd, check=True)
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['aur', 'sync', '--no-build', '--no-ver-argv', 'zig-dev-bin']' returned non-zero exit status 1.
```

`aur sync` itself works completely fine. This error did not appear in older bash version of `sync-rebuild`

**Comment by AladW** [comment]
https://unix.stackexchange.com/a/38580
